//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalServiceProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TeknikServisDBEntities : DbContext
    {
        public TeknikServisDBEntities()
            : base("name=TeknikServisDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBLAdmin> TBLAdmin { get; set; }
        public virtual DbSet<TBLBillingDetail> TBLBillingDetail { get; set; }
        public virtual DbSet<TBLBillingInfo> TBLBillingInfo { get; set; }
        public virtual DbSet<TBLCari> TBLCari { get; set; }
        public virtual DbSet<TBLCategory> TBLCategory { get; set; }
        public virtual DbSet<TBLDepartment> TBLDepartment { get; set; }
        public virtual DbSet<TBLExpense> TBLExpense { get; set; }
        public virtual DbSet<TBLFaultDetail> TBLFaultDetail { get; set; }
        public virtual DbSet<TBLNotes> TBLNotes { get; set; }
        public virtual DbSet<TBLPersonnel> TBLPersonnel { get; set; }
        public virtual DbSet<TBLProduct> TBLProduct { get; set; }
        public virtual DbSet<TBLProductAcceptance> TBLProductAcceptance { get; set; }
        public virtual DbSet<TBLProductMovement> TBLProductMovement { get; set; }
        public virtual DbSet<TBLProductTracking> TBLProductTracking { get; set; }
        public virtual DbSet<TBLAboutMe> TBLAboutMe { get; set; }
        public virtual DbSet<TBLContact> TBLContact { get; set; }
    
        public virtual ObjectResult<urunkategori_Result> urunkategori()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<urunkategori_Result>("urunkategori");
        }
    }
}
