//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalServiceProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLProductTracking
    {
        public int TAKIPID { get; set; }
        public Nullable<int> URUN { get; set; }
        public string DURUM { get; set; }
        public Nullable<int> TARIH { get; set; }
        public string TAKIPKODU { get; set; }
    
        public virtual TBLProduct TBLProduct { get; set; }
    }
}
